<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the tenement_water_types table
 *
 * automatically generated by ModelGenerator.php
 */
class TenementWaterType extends Model
{
    protected $table = 'tenement_water_types';

    protected $fillable = array('id', 'water_type','water_code',  'tenement_id', 'comment', 'activation', 'created_by', 'updated_by');

}

