<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the tenement_equipments table
 *
 * automatically generated by ModelGenerator.php
 */
class TenementEquipment extends Model
{
    protected $table = 'tenement_equipments';

    protected $fillable = array('tenement_id', 'equipment_group_id', 'equipment_type_id', 'equipment_code', 'name',
        'producer_id', 'producer' , 'label', 'model', 'specification', 'area', 'comment', 'activation', 'created_by', 'updated_by');

}

