<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the tenement_water_tariff table
 *
 * automatically generated by ModelGenerator.php
 */
class TenementWaterTariff extends Model
{
    protected $table = 'tenement_water_tariff';

    protected $fillable = array('tenement_id', 'water_type_id', 'index_from', 'index_to', 'name', 'price', 'other_fee01', 'other_fee02',
        'enviroment_fee', 'vat', 'comment', 'activation', 'created_by', 'updated_by', 'other_fee01_price', 'other_fee02_price','vat_price');

}

