<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the tenement_service_types table
 *
 * automatically generated by ModelGenerator.php
 */
class TenementServiceType extends Model
{
    protected $table = 'tenement_service_types';

    protected $fillable = array('tenement_id','service_type_name','additional_flg','comment','activation','created_at','updated_at','created_by','updated_by');
}

