<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the tenement_equipment_maintenance table
 *
 * automatically generated by ModelGenerator.php
 */
class TenementEquipmentMaintenance extends Model
{
    protected $table = 'tenement_equipment_maintenance';

    public function getDates()
    {
        return array('plan_date', 'report_date');
    }

    protected $fillable = array('equipment_id', 'plan_date', 'plan_start_time', 'plan_end_time', 'report_date', 'plan_company_execute', 'plan_for', 'plan_description', 'report_description',
        'report_start_time', 'report_end_time', 'report_by_id', 'report_by', 'report_by_company', 'category1_id',
        'category1_note', 'category2_id', 'category2_note', 'category3_id', 'category3_note', 'note', 'comment', 'activation',
        'created_by', 'updated_by');

}

