<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the tenement_flats_import table
 *
 * automatically generated by ModelGenerator.php
 */
class TenementFlatsImport extends Model
{
    protected $table = 'tenement_flats_import';

    protected $fillable = array('tenement_id', 'flat_code', 'name', 'owner' ,'address', 'phone', 'area', 'persons', 'comment', 'receive_date','elec_type_id', 'water_type_id', 'gas_type_id', 'elec_code', 'water_code', 'gas_code','token', 'activation', 'created_by', 'updated_by', 'email','contact', 'contract');

}

