<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the tenement_service_books table
 *
 * automatically generated by ModelGenerator.php
 */
class TenementServiceBook extends Model
{
    protected $table = 'tenement_service_books';

    protected $fillable = array('service_id','flat_id','book_no','price','customer','book_date','receiver','book_status','use_from_date','use_from_time','use_to_date','use_to_time','note','comment','activation','created_at','updated_at','created_by','updated_by');

}

