<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the tenement_gas_tariff table
 *
 * automatically generated by ModelGenerator.php
 */
class TenementGasTariff extends Model
{
    protected $table = 'tenement_gas_tariff';

    protected $fillable = array('gas_type_id', 'name', 'index_from', 'price', 'other_fee01', 'other_fee02', 'vat',
        'comment', 'activation', 'created_by', 'updated_by');

}

