<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the tenement_flats table
 *
 * automatically generated by ModelGenerator.php
 */
class TenementFlat extends Model
{
    protected $table = 'tenement_flats';

    protected $fillable = array('tenement_id', 'flat_code', 'name', 'owner', 'address', 'phone', 'area', 'manager_price','block_name','floor_num','floor_name','flat_num','persons', 'comment', 'water_type_id', 'display_code', 'receive_date', 'sum_pre_paid', 'elec_type_id', 'investor','is_stay', 'gas_type_id', 'bill_no', 'activation', 'created_by', 'updated_by', 'next_water_type_id', 'next_water_type_year_month','rent_status','rent_from','rent_to','rent_note','manager_fee_recal_flg');
}

