<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the tenement_water_tariff table
 *
 * automatically generated by ModelGenerator.php
 */
class TenementParkingTariff extends Model
{
    protected $table = 'tenement_parking_tariff';

    protected $fillable = array('tenement_id', 'parking_code', 'name', 'price', 'comment', 'activation', 'created_by', 'updated_by');

}

