<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the tenement_gas_types table
 *
 * automatically generated by ModelGenerator.php
 */
class TenementGasType extends Model
{
    protected $table = 'tenement_gas_types';

    protected $fillable = array('tenement_id', 'gas_type', 'gas_code', 'comment', 'activation', 'created_by', 'updated_by');

}

