<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the tenement_producers table
 *
 * automatically generated by ModelGenerator.php
 */
class TenementProducer extends Model
{
    protected $table = 'tenement_producers';

    protected $fillable = array('tenement_id', 'producer_code', 'name', 'address', 'contact_name', 'tel', 'email',
        'comment', 'activation', 'created_by', 'updated_by');

}

