<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the tenement_equipment_maintenance table
 *
 * automatically generated by ModelGenerator.php
 */
class TenementDailyActivity extends Model
{
    protected $table = 'tenement_daily_activity';

    public function getDates()
    {
        return array('daily_date');
    }

    protected $fillable = array('name', 'daily_date', 'description', 'charge_for', 'company_execute', 'tenement_id', 'start_time', 'end_time', 'report_by', 'report_by_company', 'category1_id', 'category1_note', 'category2_id', 'category2_note', 'category3_id', 'category3_note', 'note', 'comment', 'activation', 'created_by', 'updated_by');
}

