<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the tf_paid_hd table
 *
 * automatically generated by ModelGenerator.php
 */
class TfDeptSkipHd extends Model
{
    protected $table = 'tf_dept_skip_hd';

    protected $fillable = array('flat_id', 'year_month', 'money', 'skip_date', 'skip_from', 'comment', 'reason', 'activation', 'created_by', 'updated_by', 'prepaid_flg');
}

