<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the tf_elec_used table
 *
 * automatically generated by ModelGenerator.php
 */
class TfElecUsed extends Model
{
    protected $table = 'tf_elec_used';

    protected $fillable = array('flat_id', 'year_month', 'date_from', 'date_to', 'old_index', 'new_index', 'comment', 'activation', 'created_by', 'updated_by');

}

