<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the tf_elec_used_import table
 *
 * automatically generated by ModelGenerator.php
 */
class TfElecUsedImport extends Model
{
    protected $table = 'tf_elec_used_import';

    protected $fillable = array('tenement_id', 'flat_id', 'year_month', 'date_from', 'date_to', 'old_index', 'new_index', 'comment', 'token', 'activation', 'created_by', 'updated_by');

}

