<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the tf_paid_hd table
 *
 * automatically generated by ModelGenerator.php
 */
class TfPaidHd extends Model
{
    protected $table = 'tf_paid_hd';

    protected $fillable = array('flat_id', 'bill_no', 'year_month', 'money', 'receive_date', 'receive_from', 'receiver',
        'comment', 'paid_type', 'dept', 'office', 'book_bill', 'paymenter', 'reason', 'rate', 'address', 'paid_code',
        'activation', 'created_by', 'updated_by', 'prepaid_flg');

}

