<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the tf_paid_dt table
 *
 * automatically generated by ModelGenerator.php
 */
class TfResidentDt extends Model
{
    protected $table = 'tf_resident_dt';

    protected $fillable = array('resident_id','name','dob','sex','res_type','email','phone','contact','comment','activation','created_at','updated_at','created_by','updated_by','identity_card', 'date_issue', 'issued_by');

}