<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the tf_paid_hd table
 *
 * automatically generated by ModelGenerator.php
 */
class TfResidentHd extends Model
{
    protected $table = 'tf_resident_hd';

    protected $fillable = array('flat_id','stay_type','input_date','content','comment','activation','created_at','updated_at','created_by','updated_by');

}

