<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the tf_service_used table
 *
 * automatically generated by ModelGenerator.php
 */
class TfServiceUsed extends Model
{
    protected $table = 'tf_service_used';

    protected $fillable = array('flat_id','year_month', 'name', 'mount',
        'price', 'total', 'comment', 'unit', 'activation', 'created_by', 'updated_by', 'date_from', 'date_to');
}

