<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the tf_vehicle table
 *
 * automatically generated by ModelGenerator.php
 */
class TfVehicle extends Model
{
    protected $table = 'tf_vehicle';

    protected $fillable = array('flat_id', 'vehicle_type_id', 'vehicle_type_code','flat_code', 'number_plate', 'name', 'label', 'maker', 'color', 'begin_contract_date', 'end_contract_date', 'driver', 'comment', 'activation', 'created_by', 'updated_by');
}

