<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the tenement_flats table
 *
 * automatically generated by ModelGenerator.php
 */
class UserNote extends Model
{
    protected $table = 'user_notes';

    protected $fillable = array('user_id', 'content', 'note_date', 'color', 'comment',  'activation', 'created_by', 'updated_by');
}